schema_version = "1.0.0"
id = "jxsg_cliffs_generator"
version = "1.0.0"
name = "JXSG Cliffs Generator"
tagline = "Anything Generator"
maintainer = "Geek Lab <jx.geek.lab@gmail.com>"
type = "add-on"
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
